services:
  - type: web
    name: parent-profile-generator
    env: python
    buildCommand: pip install -r webapp/requirements.txt
    startCommand: bash run.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 